version: "3"
services:
  httpd:
    image: httpd:2.4.39
    command: ["tail", "-f", "--retry", "/usr/local/apache2/logs/error_log"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - docker-net
    volumes:
      - "./files/mod_dispatcher.so:/usr/local/apache2/modules/mod_dispatcher.so"
      - "./cache:/opt/aem/dispatcher/cache"
      - "./logs:/usr/local/apache2/logs"
      - "../../gradle/environment/httpd/conf:/usr/local/apache2/conf"
networks:
  docker-net:
