version: "3"
services:
  dispatcher:
    image: mierzwid/dispatcher:0.0.3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - "80:80"
    networks:
    - docker-net
networks:
  docker-net:
